name: dependencies
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter 
  
  analytics:
    path: ../../analytics
  
  crashlytics:
    path: ../../crashlytics
  
  deeplinks:
    path: ../../deeplinks
  
  notifications:
    path: ../../notifications
  
  utils:
    path: ../../utils
  
  common:
    path: ../common
  
  dependency_injection:
    path: ../dependency_injection
  
  key_value_storage:
    path: ../key_value_storage
  
  networking: 
    path: ../networking
  
  secure_storage:
    path: ../secure_storage
  
  ui_components:
    path: ../ui_components
  universal_platform: ^1.1.0
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.3
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
