name: monorepo

packages:
  - apps/**
  - packages/**

scripts:
  build_runner:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    select-package:
      depends-on: build_runner

  upgrade:
    run: melos exec -- flutter pub upgrade .
    description: Run `flutter pub upgrade` in all packages.

  cache_clean:
    run: melos exec -- flutter pub cache clean -f .
    description: Run `flutter pub cache clean` in all packages.

  remove_lock:
    run: melos exec -- rm pubspec.lock
    description: Remove all the pubspec.lock files.