name: dependency_injection
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
