name: common
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  logger: ^2.4.0
  permission_handler: ^11.3.1
  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_lints: ^3.0.0