name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dependencies:
    path: ../../packages/core/dependencies
  
  flutter_native_splash: ^2.4.1
  statsfl: ^2.3.0
  go_router: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
